# Site settings
title: Gerardo Santoveña
email: gsantovena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Gerardo Santoveña and this is where I write about my
  life in IT. A little bit of development, and a little bit about systems 
  administration. You will see here resolution to common problems, scripts,
  tips and tricks and anything that goes through my mind.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gsantovena.github.io" # the base hostname & protocol for your site
twitter_username: gsantovena
github_username:  gsantovena

# Build settings
markdown: kramdown
