# Site settings
title: Gerardo Santoveña
email: gsantovena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Gerardo Santoveña and this is my GitHub page.

  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gsantovena.github.io" # the base hostname & protocol for your site
twitter_username: gsantovena
github_username:  gsantovena

# Build settings
markdown: kramdown
